{% set name = "ipyleaflet-gl-vector-layer-plugin" %}
{% set version = "0.1.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stcorp/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 8f3d96bd3af45c4fdc2f61e4bfeb5ffb7b12b9677c104bc4e2a4da08499bf039

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools >=40.8.0
    - jupyter-packaging ~=0.7.9
    - jupyterlab >=3.0.0,<4
    - yarn <2
  run:
    - python >=3.6
    - ipywidgets >=7.6.0
    - ipyleaflet >=0.13.5
    - traittypes
    - traitlets
    - numpy

test:
  imports:
    - ipyleaflet_gl_vector_layer
  commands:
    - test -f ${PREFIX}/share/jupyter/nbextensions/@stcorp/ipyleaflet-gl-vector-layer-plugin/extension.js                             # [unix]
    - test -f ${PREFIX}/share/jupyter/nbextensions/@stcorp/ipyleaflet-gl-vector-layer-plugin/index.js                                 # [unix]
    - test -f ${PREFIX}/share/jupyter/labextensions/@stcorp/ipyleaflet-gl-vector-layer-plugin/package.json                            # [unix]
    - if not exist %PREFIX%\\share\\jupyter\\nbextensions\\@stcorp/ipyleaflet-gl-vector-layer-plugin\\extension.js (exit 1)           # [win]
    - if not exist %PREFIX%\\share\\jupyter\\nbextensions\\@stcorp/ipyleaflet-gl-vector-layer-plugin\\index.js (exit 1)               # [win]
    - if not exist %PREFIX%\\share\\jupyter\\labextensions\\@stcorp/ipyleaflet-gl-vector-layer-plugin\\package.json (exit 1)          # [win]

about:
  home: https://github.com/stcorp/ipyleaflet-gl-vector-layer-plugin
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A plugin for visualizing large amounts of data on a GL-overlay on top of Leaflet

extra:
  recipe-maintainers:
    - srepmub
    - svniemeijer
